set __COMPAT_LAYER=WIN7RTM
lcc -Wa-l -Iinclude -DCGB -c -o obj/Actor_a.o src/core/Actor_a.s
lcc -Wa-l -Iinclude -DCGB -c -o obj/Actor_b.o src/core/Actor_b.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Actor.o src/core/Actor.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/asm.macros.o src/core/asm.macros.s
lcc -Wa-l -Iinclude -DCGB -c -o obj/BankData.o src/core/BankData.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/BankManager.o src/core/BankManager.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Camera_a.o src/core/Camera_a.s
lcc -Wa-l -Iinclude -DCGB -c -o obj/Camera.o src/core/Camera.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Collision.o src/core/Collision.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Core_Main.o src/core/Core_Main.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/DataManager.o src/core/DataManager.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/FadeManager_b.o src/core/FadeManager_b.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/FadeManager.o src/core/FadeManager.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/gbt_player_bank1.o src/core/gbt_player_bank1.s
lcc -Wa-l -Iinclude -DCGB -c -o obj/gbt_player.o src/core/gbt_player.s
lcc -Wa-l -Iinclude -DCGB -c -o obj/Input.o src/core/Input.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Math.o src/core/Math.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/MusicManager.o src/core/MusicManager.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Palette.o src/core/Palette.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Projectiles_b.o src/core/Projectiles_b.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Projectiles.o src/core/Projectiles.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/ScriptRunner_b.o src/core/ScriptRunner_b.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/ScriptRunner.o src/core/ScriptRunner.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Scroll_a.o src/core/Scroll_a.s
lcc -Wa-l -Iinclude -DCGB -c -o obj/Scroll_b.o src/core/Scroll_b.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Scroll.o src/core/Scroll.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Sprite_b.o src/core/Sprite_b.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Sprite.o src/core/Sprite.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Stack.o src/core/Stack.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Trigger_b.o src/core/Trigger_b.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Trigger.o src/core/Trigger.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/UI_b.o src/core/UI_b.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/UI.o src/core/UI.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/data_ptrs.o src/data/data_ptrs.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/main.o src/main.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Adventure.o src/states/Adventure.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Platform.o src/states/Platform.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/PointNClick.o src/states/PointNClick.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/Shmup.o src/states/Shmup.c
lcc -Wa-l -Iinclude -DCGB -c -o obj/TopDown.o src/states/TopDown.c
lcc -Wl-yo16 -Wa-l -Wl-m -Wl-j -Wl-yt27 -Wl-ya4 -Wm-yc -o build/rom/game.gb obj/Actor_a.o obj/Actor_b.o obj/Actor.o obj/asm.macros.o obj/BankData.o obj/BankManager.o obj/Camera_a.o obj/Camera.o obj/Collision.o obj/Core_Main.o obj/DataManager.o obj/FadeManager_b.o obj/FadeManager.o obj/gbt_player_bank1.o obj/gbt_player.o obj/Input.o obj/Math.o obj/MusicManager.o obj/Palette.o obj/Projectiles_b.o obj/Projectiles.o obj/ScriptRunner_b.o obj/ScriptRunner.o obj/Scroll_a.o obj/Scroll_b.o obj/Scroll.o obj/Sprite_b.o obj/Sprite.o obj/Stack.o obj/Trigger_b.o obj/Trigger.o obj/UI_b.o obj/UI.o obj/bank_6.o obj/bank_7.o obj/data_ptrs.o obj/main.o obj/music_bank_8.o obj/Adventure.o obj/Platform.o obj/PointNClick.o obj/Shmup.o obj/TopDown.o